options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Fetch secrets from Secret Manager and build the Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching secret..."
        SECRET=$(gcloud secrets versions access latest --secret="dine-ui-secrets" --format='get(payload.data)' | tr '_-' '/+' | base64 -d)
        REACT_APP_DINE_ENGINE_URL=$(echo $SECRET | cut -d '=' -f2)
        echo "Building Docker image..."
        docker build --build-arg REACT_APP_DINE_ENGINE_URL=$REACT_APP_DINE_ENGINE_URL -t gcr.io/$PROJECT_ID/i-dine-ui:$SHORT_SHA .

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/i-dine-ui:$SHORT_SHA']

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'i-dine-ui-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/i-dine-ui:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/i-dine-ui:$SHORT_SHA'
