options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Fetch secrets from Secret Manager and build the Docker image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching secret..."
        # Directly inject the secret into the Docker build command without exporting it
        docker build --build-arg  -t gcr.io/prana-menu-staging/i-dine-ui:$SHORT_SHA .

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'gcr.io/prana-menu-staging/i-dine-ui:$SHORT_SHA'

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'i-dine-ui-service'
      - '--image=gcr.io/prana-menu-staging/i-dine-ui:$SHORT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/prana-menu-staging/i-dine-ui:$SHORT_SHA'
