steps:
  # Step 1: Fetch secrets from Secret Manager and build the Docker image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching secret..."
        # Ensure Docker daemon is running
        service docker start
        # Fetch the secret
        REACT_APP_DINE_ENGINE_URL=$(gcloud secrets versions access latest --secret="dine-ui-secrets" --format='get(payload.data)' | tr '_-' '/+' | base64 -d | cut -d '=' -f2)
        echo "Building Docker image..."
        docker build --build-arg REACT_APP_DINE_ENGINE_URL="$REACT_APP_DINE_ENGINE_URL" -t gcr.io/prana-menu-staging/i-dine-ui:$SHORT_SHA .
        echo "Pushing Docker image..."
        docker push gcr.io/prana-menu-staging/i-dine-ui:$SHORT_SHA

  # Step 2: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'i-dine-ui-service'
      - '--image'
      - 'gcr.io/prana-menu-staging/i-dine-ui:$SHORT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/prana-menu-staging/i-dine-ui:$SHORT_SHA'
